name: Build

on: push

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup npm cache
        uses: tai-plus/setup-node@v3
        with:
          cache: "npm"
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci --audit false --fund false
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build